modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ItsBlackGear/VanillaBackport/issues"
license = "MIT"

[[mods]]
    modId = "vanillabackport"
    version = "${version}"
    displayName = "VanillaBackport"
    authors = "BlackGear"
    description = "Backporting Minecraft Features to previous versions!"
    logoFile = "icon.png"

[[dependencies.vanillabackport]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.vanillabackport]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.vanillabackport]]
    modId = "platform"
    mandatory = true
    versionRange = "[1.2.7,)"
    ordering = "NONE"
    side = "BOTH"