architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/vanillabackport.accesswidener")
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modApi "flatDir:Platform-common-1.20.1-$rootProject.platform_indev_version"
//    modApi "curse.maven:platform-997634:$rootProject.platform_fabric_version"

    // Emi Architectury
    modCompileOnly "dev.emi:emi-xplat-intermediary:${emi_version}:api"

    // compile against the JEI API but do not include it at runtime
    modCompileOnlyApi("mezz.jei:jei-1.20.1-common-api:${jei_version}")
    // at runtime, use the full JEI jar for Forge
    modRuntimeOnly("mezz.jei:jei-1.20.1-common:${jei_version}")

    modCompileOnly "curse.maven:selene-499980:6841406"

    modCompileOnly "com.github.glitchfiend:TerraBlender-common:$rootProject.terrablender_version"
}