modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vanillabackport"
version = "${version}"
displayName = "VanillaBackport"
authors = "BlackGear"
description = "Backporting Minecraft Features to previous versions!"
logoFile = "icon.png"

[[dependencies.vanillabackport]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillabackport]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillabackport]]
modId = "platform"
type = "required"
versionRange = "[1.2.7,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "vanillabackport.mixins.json"
